import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

declare global {
  interface Window {
    onLicenseSuspended?: (status: unknown) => void;
  }
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        {/* Register onLicenseSuspended before the guard script loads */}
        <Script id="license-guard-setup" strategy="beforeInteractive">
          {`window.onLicenseSuspended = function(status) {
            console.warn('License suspended:', status);
          };`}
        </Script>
        <Script
          src="https://license-tau-nine.vercel.app/guard.js"
          data-api-key="6200e059-17d6-43c6-a0d8-2012e383d549"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
