// ⚡ Auto-generated by @masdannn/license-guard — JANGAN DIHAPUS
import { initGuard } from '@masdannn/license-guard';

if (typeof window !== 'undefined') {
  initGuard({
    apiKey: 'LG-9250b9ef7630d5ce9cb63a28704fc0830f52779264d66690',
    endpoint: 'https://license-tau-nine.vercel.app',
  });
}
