// ⚡ Auto-generated by @masdannn/license-guard — JANGAN DIHAPUS
import { initGuard } from '@masdannn/license-guard';

if (typeof window !== 'undefined') {
  initGuard({
    key: 'LGK_eCUyNmR2bkNseiUyNiUzRiUyNEtPJTI0NjEzMmE4JTNEMzI2NTQlM0ElM0YwYTEwZWtrZ2cwMzQlM0IlM0RmNmc1ZCUzRDAzMzY3MCUzRmwxNTM2MG4lMkIlMkYlMjYlNjBoY3hmampxJTI0JTNEKmF3cHV1JTNEJyUyNm9tZmNpJTdCbC5wZHMqZiU2MG1hJTJCcGJ6amZoJTJCZ3d4JTJCJTJGJTI2YWlqaSU2MG0lMjYlM0YlMjRjJTdEZG4lN0QlMjVicmklMkJ+',
  });
}
