'use client';

// ⚡ Auto-generated by @masdannn/license-guard — JANGAN DIHAPUS
import { initGuard } from '@masdannn/license-guard';

if (typeof window !== 'undefined') {
  initGuard({
    key: 'LGK_ZHtJbGZGbk9eXWprTG1PTFB6NWxYeGR8SHtYa11/ZW9MU0h7THlNfU9oQWxIVUt7XTdbbk1AYnZNR15uT3hRbUhsV3lJUWVvWW5UMkxEQTFPMEptSUJIb2ZoU3VhNml0ZkBNM0hvazRhSUB5S2w5dGFDaWtYVDF/W1EyNFxZV3dmaG13WVcwM1hbTm9bVXRxXFlAdE1sdmtZQzx1W1RocEhobG1fSVR3Zl1qdmdDU3tmRGhwW3syc1xWZm9IaDRuZ0N9cVhtb3BYWkFzTG8yPg==',
  });
}
